i) single line comment
# Hello, My name is utam patel...
# I am from morbi...
# I am study in atmiya university...

ii) 1) multiline comment
'''Hello, My name is utam patel...
I am from morbi...
I am study in atmiya university...'''

ii) 2) multiline comment
"""Hello, My name is utam patel...
I am from morbi...
I am study in atmiya university..."""